// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohafadati.Services.Titres.Data;

#nullable disable

namespace Mohafadati.Services.Titres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714141703_AddTitreToDb")]
    partial class AddTitreToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mohafadati.Services.Titres.Models.Titre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConservationFonciere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndiceSpecial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTitre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Titres");
                });
#pragma warning restore 612, 618
        }
    }
}
