// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohafadati.Services.Titres.Data;

#nullable disable

namespace Mohafadati.Services.Titres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mohafadati.Services.Titres.Models.Titre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConservationFonciere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndiceSpecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTitre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Titres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConservationFonciere = "Rabat",
                            Indice = "B1",
                            IndiceSpecial = "C",
                            NumeroTitre = 1234
                        },
                        new
                        {
                            Id = 2,
                            ConservationFonciere = "Rabat",
                            Indice = "D",
                            IndiceSpecial = "A3",
                            NumeroTitre = 4321
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
